CAPACITY_PV_KWP = "capacity_pv_kWp"
CAPACITY_WIND_KW = "capacity_wind_kW"
CAPACITY_STORAGE_KWH = "capacity_storage_kWh"
POWER_STORAGE_KW = "power_storage_kW"
CAPACITY_GENSET_KW = "capacity_genset_kW"
CAPACITY_PCOUPLING_KW = "capacity_pcoupling_kW"
CAPACITY_RECTIFIER_AC_DC_KW = "capacity_rectifier_ac_dc_kW"
CAPACITY_INVERTER_DC_AC_KW = "capacity_inverter_dc_ac_kW"
DEMAND_PROFILE = "demand_profile"

SETTINGS ="settings"
INPUT_CONSTANT = "input_constant"
INPUT_SENSITIVITY = "input_sensitivity"
PROJECT_SITES = "project_sites"
CASE_DEFINITIONS = "case_definitions"
MULTICRITERIA_DATA = "multicriteria_data"
INPUT_FOLDER_TIMESEREIES = "input_folder_timeseries"
TIMESERIES_FILE = "timeseries_file"